services:
  builder:
    image: ghcr.io/sinicaphak/local_proxy:latest
    volumes:
      - ../:/home/tester/local_proxy
    working_dir: /home/tester/local_proxy
    command: >-
      /bin/bash -c '
        findmnt /home/tester/local_proxy
      '