name: Build Pack, and Release

on:
  push:
    paths:
      - '.github/workflows/release.yml'
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Show Current Directory
        run: |
          echo "Current Path: $(pwd)"
          echo "github.workspace: ${{ github.workspace }}"
          ls -F

      - name: Build with Docker Compose
        run: |
          docker compose -f pack_env/docker_compose.yml up --exit-code-from builder
          
      - name: Check output
        run: ls -l dist/

      - name: Release
        if: hashFiles('dist/*.deb') != ''
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.deb
          tag_name: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}